name: rxdart
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.0-231.0.dev <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  logging: ^1.2.0
  quiver: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
